/**
 * Base64Feature — Auto-generated by Plugin Generator
 *
 * Template: transform
 * Extends BaseFeature from Feature SDK.
 * ALL capabilities via this.context. Zero Core/Registry/Service access.
 *
 * Spec-aligned: encode/decode dispatch via config.mode.
 * No process() — uses encode(), decode(), validate(), validateBase64().
 */

import {
  BaseFeature,
  type FeatureContext,
  type FeatureState,
  type ValidationResult,
} from '@/sdk/feature'

import type { Base64Config, Base64State, Base64Result } from './types'
import { defaults } from './settings'
import { encode, decode, validate, validateBase64, getStats } from './logic'

export class Base64Feature extends BaseFeature<Base64Config, string, Base64Result> {
  private _toolState: Base64State

  constructor(context: FeatureContext<Base64Config>) {
    super(context, defaults)
    this._toolState = { input: '', output: null, inputSize: 0, outputSize: null }
  }

  get toolState(): Readonly<Base64State> { return this._toolState }

  // ── Lifecycle ─────────────────────────────────────────────────────

  async initialize(): Promise<void> {
    await this.context.settings.load()
    const saved = await this.context.settings.load()
    this._config = { ...defaults, ...saved }
    this.lifecycle.transition('initialized')
    this.context.logger.info('Base64Feature initialized')
  }

  async activate(): Promise<void> {
    this.lifecycle.transition('active')
    this.context.notification.info('Base64', 'Encode and decode text to/from Base64 with full Unicode support')
  }

  async deactivate(): Promise<void> { this.saveState(); this.lifecycle.transition('inactive') }
  async dispose(): Promise<void> { this.reset(); this.lifecycle.transition('disposed') }

  // ── Core Logic ────────────────────────────────────────────────────

  /**
   * Sole execution entry point.
   * Dispatches encode() or decode() based on config.mode.
   */
  async run(input: string, config: Base64Config): Promise<Base64Result> {
    let output: string

    if (config.mode === 'decode') {
      const b64Result = validateBase64(input)
      if (!b64Result.valid) {
        throw new Error(b64Result.error!.message)
      }
      output = decode(input)
    } else {
      const padding = config.padding ?? 'standard'
      output = encode(input, { padding })
    }

    const stats = getStats(output)
    this._toolState.outputSize = stats.bytes

    return { output, stats }
  }

  validate(input: string): ValidationResult {
    return validate(input)
  }

  transform(input: string, _config: Base64Config): string {
    const s = getStats(input)
    this._toolState.inputSize = s.bytes
    return input
  }

  preview(_input: string, _config: Base64Config): Base64Result | null { return null }
  cancel(): void { this.setIdle() }

  saveState(): FeatureState<Base64Result> { return { ...this._state } }
  loadState(state: FeatureState<Base64Result>): void { this._state = { ...state } }
  reset(): void {
    this._state = { phase: 'idle', input: '', output: null, error: null, progress: null }
    this._toolState = { input: '', output: null, inputSize: 0, outputSize: null }
  }

  // ── History ───────────────────────────────────────────────────────

  recordHistory(): void {
    this.context.history.add({
      input: this._state.input,
      output: this._state.output?.output ?? null,
      config: { ...this._config },
      timestamp: Date.now(),
    })
  }
}
