/**
 * HashFeature — Auto-generated by Plugin Generator
 *
 * Template: transform
 * Extends BaseFeature from Feature SDK.
 * ALL capabilities via this.context. Zero Core/Registry/Service access.
 *
 * Spec-aligned: MD5 / SHA-256 dispatch via config.algorithm.
 */

import {
  BaseFeature,
  type FeatureContext,
  type FeatureState,
  type ValidationResult,
} from '@/sdk/feature'

import type { HashConfig, HashState, HashResult } from './types'
import { defaults } from './settings'
import { hashText, validateHashInput, getStats } from './logic'

export class HashFeature extends BaseFeature<HashConfig, string, HashResult> {
  private _toolState: HashState

  constructor(context: FeatureContext<HashConfig>) {
    super(context, defaults)
    this._toolState = { input: '', output: null, inputSize: 0, outputSize: null }
  }

  get toolState(): Readonly<HashState> {
    return this._toolState
  }

  // ── Lifecycle ─────────────────────────────────────────────────────

  async initialize(): Promise<void> {
    await this.context.settings.load()
    const saved = await this.context.settings.load()
    this._config = { ...defaults, ...saved }
    this.lifecycle.transition('initialized')
    this.context.logger.info('HashFeature initialized')
  }

  async activate(): Promise<void> {
    this.lifecycle.transition('active')
    this.context.notification.info('Hash', 'Generate MD5 and SHA-256 hashes')
  }

  async deactivate(): Promise<void> {
    this.saveState()
    this.lifecycle.transition('inactive')
  }

  async dispose(): Promise<void> {
    this.reset()
    this.lifecycle.transition('disposed')
  }

  // ── Core Logic ────────────────────────────────────────────────────

  /**
   * Sole execution entry point.
   * Dispatches md5() or sha256() based on config.algorithm.
   */
  async run(input: string, config: HashConfig): Promise<HashResult> {
    const result = await hashText(input, config)
    const stats = getStats(result.output)
    this._toolState.outputSize = stats.bytes

    return result
  }

  validate(input: string): ValidationResult {
    return validateHashInput(input)
  }

  transform(input: string, _config: HashConfig): string {
    const s = getStats(input)
    this._toolState.inputSize = s.bytes
    return input
  }

  preview(_input: string, _config: HashConfig): HashResult | null {
    return null
  }

  cancel(): void {
    this.setIdle()
  }

  saveState(): FeatureState<HashResult> {
    return { ...this._state }
  }

  loadState(state: FeatureState<HashResult>): void {
    this._state = { ...state }
  }

  reset(): void {
    this._state = {
      phase: 'idle',
      input: '',
      output: null,
      error: null,
      progress: null,
    }
    this._toolState = { input: '', output: null, inputSize: 0, outputSize: null }
  }

  // ── History ───────────────────────────────────────────────────────

  recordHistory(): void {
    this.context.history.add({
      input: this._state.input,
      output: this._state.output?.output ?? null,
      config: { ...this._config },
      timestamp: Date.now(),
    })
  }
}
