/**
 * UrlFeature — Auto-generated by Plugin Generator
 *
 * Template: transform
 * Extends BaseFeature from Feature SDK.
 * ALL capabilities via this.context. Zero Core/Registry/Service access.
 *
 * Spec-aligned: encode/decode dispatch via config.mode.
 * Supports both component and URI variants.
 */

import {
  BaseFeature,
  type FeatureContext,
  type FeatureState,
  type ValidationResult,
} from '@/sdk/feature'

import type { UrlConfig, UrlState, UrlResult } from './types'
import { defaults } from './settings'
import { transformUrl, validateUrlInput, validateDecodeInput, getStats } from './logic'

export class UrlFeature extends BaseFeature<UrlConfig, string, UrlResult> {
  private _toolState: UrlState

  constructor(context: FeatureContext<UrlConfig>) {
    super(context, defaults)
    this._toolState = { input: '', output: null, inputSize: 0, outputSize: null }
  }

  get toolState(): Readonly<UrlState> {
    return this._toolState
  }

  // ── Lifecycle ─────────────────────────────────────────────────────

  async initialize(): Promise<void> {
    await this.context.settings.load()
    const saved = await this.context.settings.load()
    this._config = { ...defaults, ...saved }
    this.lifecycle.transition('initialized')
    this.context.logger.info('UrlFeature initialized')
  }

  async activate(): Promise<void> {
    this.lifecycle.transition('active')
    this.context.notification.info('URL', 'Encode and decode URLs using URI or component modes')
  }

  async deactivate(): Promise<void> {
    this.saveState()
    this.lifecycle.transition('inactive')
  }

  async dispose(): Promise<void> {
    this.reset()
    this.lifecycle.transition('disposed')
  }

  // ── Core Logic ────────────────────────────────────────────────────

  /**
   * Sole execution entry point.
   * Dispatches encodeUrl() or decodeUrl() based on config.mode + config.variant.
   */
  async run(input: string, config: UrlConfig): Promise<UrlResult> {
    // Pre-validate decode input for malformed percent encoding
    if (config.mode === 'decode') {
      const decodeValidation = validateDecodeInput(input, config.variant)
      if (!decodeValidation.valid) {
        throw new Error(decodeValidation.errors![0].message)
      }
    }

    const result = transformUrl(input, config)
    const stats = getStats(result.output)
    this._toolState.outputSize = stats.bytes

    return result
  }

  validate(input: string): ValidationResult {
    return validateUrlInput(input)
  }

  transform(input: string, _config: UrlConfig): string {
    const s = getStats(input)
    this._toolState.inputSize = s.bytes
    return input
  }

  preview(_input: string, _config: UrlConfig): UrlResult | null {
    return null
  }

  cancel(): void {
    this.setIdle()
  }

  saveState(): FeatureState<UrlResult> {
    return { ...this._state }
  }

  loadState(state: FeatureState<UrlResult>): void {
    this._state = { ...state }
  }

  reset(): void {
    this._state = {
      phase: 'idle',
      input: '',
      output: null,
      error: null,
      progress: null,
    }
    this._toolState = { input: '', output: null, inputSize: 0, outputSize: null }
  }

  // ── Clipboard ─────────────────────────────────────────────────────

  async copyOutput(): Promise<void> {
    const result = this._state.output
    if (result) {
      await this.context.clipboard.copy(result.output)
      this.context.notification.success('Copied', 'Output copied to clipboard')
    }
  }

  // ── History ───────────────────────────────────────────────────────

  recordHistory(): void {
    this.context.history.add({
      input: this._state.input,
      output: this._state.output?.output ?? null,
      config: { ...this._config },
      timestamp: Date.now(),
    })
  }
}
