<script setup lang="ts">
/**
 * Unicode Plugin — Main View (transform template)
 *
 * Auto-generated by Plugin Generator.
 * ALL UI from Design System. Zero custom components.
 */

import { onMounted, onUnmounted } from 'vue'
import { useUnicode } from './composables'

const { input, output, error, loading, stats, toolbar, execute, init, dispose } = useUnicode()

onMounted(() => init())
onUnmounted(() => dispose())

function onKeydown(e: KeyboardEvent) {
  if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') { e.preventDefault(); execute() }
}
</script>

<template>
  <div class="page" @keydown="onKeydown">
    <header class="page-header">
      <h1 class="page-title">Unicode</h1>
      <p class="page-desc">数据转换工具 — 输入、转换、输出 &mdash; <kbd>⌘Enter</kbd> 执行</p>
    </header>

    <div class="page-content">
      <!-- Card: Input -->
      <div class="card">
        <div class="card-header">输入</div>
        <div class="card-body">
          <textarea
            v-model="input"
            class="dt-textarea"
            rows="10"
            :placeholder="'输入要处理的数据...'"
            spellcheck="false"
          />
        </div>
      </div>

      <!-- Action Bar -->
      <div class="action-bar">
        <button class="btn-accent" @click="execute" :disabled="loading">
          <span v-if="loading" class="spinner"></span>
          {{ loading ? '处理中...' : '执行' }}
        </button>
        <button class="btn-secondary" @click="toolbar.execute('clear')">清空</button>
        <button v-if="output" class="btn-secondary" @click="toolbar.execute('copy')">复制输出</button>
        <button v-if="output" class="btn-secondary" @click="toolbar.execute('swap')">交换</button>
      </div>

      <!-- Error -->
      <div v-if="error" class="alert-error">{{ error }}</div>

      <!-- Card: Output -->
      <div class="card card-output" v-if="output">
        <div class="card-header">输出</div>
        <div class="card-body">
          <textarea :value="output" class="dt-textarea" rows="10" readonly spellcheck="false" />
        </div>
      </div>

      <!-- Empty State -->
      <div class="card" v-if="!output && !error && !input">
        <div class="card-body empty-hint">
          <p>🔐 数据转换工具 — 输入、转换、输出</p>
          <p class="hint-desc">输入内容后点击「执行」或按 <kbd>⌘Enter</kbd></p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.page { max-width: var(--content-max-width); margin: 0 auto; }
.page-header { margin-bottom: var(--space-6); }
.page-title { font-size: var(--text-title); font-weight: var(--weight-semibold); color: var(--color-neutral-110); margin-bottom: var(--space-1); letter-spacing: -0.01em; }
.page-desc { font-size: var(--text-body); color: var(--color-neutral-70); }
.page-desc kbd { font-size: var(--text-caption); padding: 1px 5px; background: var(--color-neutral-40); border: var(--border-width-thin) solid var(--border-color-default); border-radius: var(--radius-sm); font-family: var(--font-mono); }
.page-content { display: flex; flex-direction: column; gap: var(--space-3); }

.card { background: var(--color-neutral-35); border: var(--border-width-thin) solid rgba(255,255,255,0.05); border-radius: var(--radius-xl); overflow: hidden; }
.card-header { padding: 9px var(--space-5); font-size: var(--text-caption); font-weight: var(--weight-medium); color: var(--color-neutral-60); text-transform: uppercase; letter-spacing: 0.06em; border-bottom: var(--border-width-thin) solid rgba(255,255,255,0.04); }
.card-body { padding: var(--space-4) var(--space-5); }
.card-output { border-color: var(--border-color-focus); }
.card-output .card-body { background: var(--color-neutral-15); }
.card-output .card-body textarea { background: var(--color-neutral-10); border-color: var(--border-color-focus); }

.action-bar { display: flex; gap: 8px; flex-wrap: wrap; }

.empty-hint { text-align: center; padding: var(--space-8) 0; }
.empty-hint p { font-size: var(--text-base); color: var(--color-neutral-90); }
.empty-hint .hint-desc { font-size: var(--text-body); color: var(--color-neutral-70); margin-top: var(--space-1); }
</style>
