/**
 * ZentaoFeature — Auto-generated by Plugin Generator
 *
 * Template: enterprise
 * Extends BaseFeature from Feature SDK.
 * ALL capabilities via this.context. Zero Core/Registry/Service access.
 */

import {
  BaseFeature,
  type FeatureContext,
  type FeatureState,
  type ValidationResult,
} from '@/sdk/feature'

import type { ZentaoConfig, ZentaoState } from './types'
import { defaults } from './settings'
import { process, getStats } from './logic'

export class ZentaoFeature extends BaseFeature<ZentaoConfig, string, string> {
  private _toolState: ZentaoState

  constructor(context: FeatureContext<ZentaoConfig>) {
    super(context, defaults)
    this._toolState = { input: '', output: null, inputSize: 0, outputSize: null }
  }

  get toolState(): Readonly<ZentaoState> { return this._toolState }

  // ── Lifecycle ─────────────────────────────────────────────────────
  async initialize(): Promise<void> {
    await this.context.settings.load()
    const saved = await this.context.settings.load()
    this._config = { ...defaults, ...saved }
    this.lifecycle.transition('initialized')
    this.context.logger.info('ZentaoFeature initialized')
  }

  async activate(): Promise<void> {
    this.lifecycle.transition('active')
    this.context.notification.info('Zentao', 'Ready — Enterprise tool — external service integration')
  }

  async deactivate(): Promise<void> { this.saveState(); this.lifecycle.transition('inactive') }
  async dispose(): Promise<void> { this.reset(); this.lifecycle.transition('disposed') }

  // ── Core Logic ────────────────────────────────────────────────────
  async run(input: string, config: ZentaoConfig): Promise<string> {
    const result = process(input, config)
    const stats = getStats(result)
    this._toolState.outputSize = stats.size
    return result
  }

  validate(input: string): ValidationResult {
    if (!input.trim()) {
      return { valid: false, errors: [{ field: 'input', message: 'Input is empty' }] }
    }
    return { valid: true }
  }

  transform(input: string, _config: ZentaoConfig): string {
    const s = getStats(input)
    this._toolState.inputSize = s.size
    return input.trim()
  }

  preview(_input: string, _config: ZentaoConfig): string | null { return null }
  cancel(): void { this.setIdle() }

  saveState(): FeatureState<string> { return { ...this._state } }
  loadState(state: FeatureState<string>): void { this._state = { ...state } }
  reset(): void {
    this._state = { phase: 'idle', input: '', output: null, error: null, progress: null }
    this._toolState = { input: '', output: null, inputSize: 0, outputSize: null }
  }

  // ── History ───────────────────────────────────────────────────────
  recordHistory(): void {
    this.context.history.add({
      input: this._state.input,
      output: this._state.output,
      timestamp: Date.now(),
    })
  }
}
