// @ts-nocheck
/**
 * Agent Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'agent',
  name: 'Agent',
  icon: 'MessagesSquare',
  version: '1.0.0',
  description: 'AI tools — chat, completion, and generation',
  category: 'ai',
  status: 'coming-soon',

  route: '/agent',
  component: () => import('@/features/agent/AgentView.vue'),

  commands: [
    {
      id: 'agent:chat',
      label: 'Agent: Chat',
      description: 'Start AI chat',
      shortcut: 'Cmd+Enter',
    },
    {
      id: 'agent:clear',
      label: 'Agent: Clear History',
      description: 'Clear chat history',
    },
  ],

  shortcuts: [
    { commandId: 'agent:chat', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['agent', 'ai', 'chat', 'generate', 'llm', 'gpt', '智能'],

  permissions: ['ai:chat', 'network'],

  settings: {
    model: { key: 'model', type: 'select' as const, label: 'Model', default: "default" },
    temperature: { key: 'temperature', type: 'number' as const, label: 'Temperature', default: 0.7 },
  },

  history: { enabled: true, maxItems: 20 },
})
