/**
 * Color Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'color',
  name: 'Color',
  icon: '🔄',
  version: '1.0.0',
  description: '格式互转工具 — 两种格式之间互相转换',
  category: 'converter',

  route: '/color',
  component: () => import('@/features/color/ColorView.vue'),

  commands: [
    {
      id: 'color:convert',
      label: 'Color: Convert',
      description: 'Convert format',
      shortcut: 'Cmd+Enter',
    },
    {
      id: 'color:swap',
      label: 'Color: Swap Direction',
      description: 'Swap conversion direction',
    },
  ],

  shortcuts: [
    { commandId: 'color:convert', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['color', 'convert', 'converter', 'transform', 'switch', '互转'],

  permissions: ['clipboard:read', 'clipboard:write'],

  settings: {
    defaultDirection: { key: 'defaultDirection', type: 'select' as const, label: '默认方向', default: "forward" },
  },

  history: { enabled: true, maxItems: 20 },
})
