// @ts-nocheck
/**
 * Curl Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'curl',
  name: 'cURL',
  icon: 'Globe',
  version: '1.0.0',
  description: 'Network tool — HTTP request and response analysis',
  category: 'network',
  status: 'coming-soon',

  route: '/curl',
  component: () => import('@/features/curl/CurlView.vue'),

  commands: [
    {
      id: 'curl:send',
      label: 'Curl: Send Request',
      description: 'Send HTTP request',
      shortcut: 'Cmd+Enter',
    },
  ],

  shortcuts: [
    { commandId: 'curl:send', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['curl', 'http', 'request', 'api', 'curl', 'rest', 'fetch', '请求'],

  permissions: ['network', 'clipboard:write'],

  settings: {
    defaultMethod: { key: 'defaultMethod', type: 'select' as const, label: 'Default Method', default: "GET" },
    timeout: { key: 'timeout', type: 'number' as const, label: 'Timeout (ms)', default: 10000 },
  },

  history: { enabled: true, maxItems: 20 },
})
