// @ts-nocheck
/**
 * Diff Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'diff',
  name: 'Diff',
  icon: 'GitBranch',
  version: '1.0.0',
  description: 'Editor tool — format, minify, and validate',
  category: 'formatter',

  route: '/diff',
  component: () => import('@/features/diff/DiffView.vue'),

  commands: [
    {
      id: 'diff:format',
      label: 'Diff: Format',
      description: 'Format content',
      shortcut: 'Cmd+Shift+F',
    },
    {
      id: 'diff:minify',
      label: 'Diff: Minify',
      description: 'Minify/compress content',
    },
    {
      id: 'diff:validate',
      label: 'Diff: Validate',
      description: 'Validate content',
    },
  ],

  shortcuts: [
    { commandId: 'diff:format', default: 'Ctrl+Shift+F', mac: 'Cmd+Shift+F' },
  ],

  keywords: ['diff', 'format', 'minify', 'validate', 'editor', 'formatter', 'beautify'],

  permissions: ['clipboard:read', 'clipboard:write', 'file:export'],

  settings: {
    indentSize: { key: 'indentSize', type: 'select' as const, label: '缩进', default: 2 },
    autoFormat: { key: 'autoFormat', type: 'toggle' as const, label: '自动格式化', default: true },
  },

  history: { enabled: true, maxItems: 20 },
})
