// @ts-nocheck
/**
 * Explain Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'explain',
  name: 'Explain',
  icon: '🤖',
  version: '1.0.0',
  description: 'AI 工具 — 对话、补全与生成',
  category: 'generator',

  route: '/explain',
  component: () => import('@/features/explain/ExplainView.vue'),

  commands: [
    {
      id: 'explain:chat',
      label: 'Explain: Chat',
      description: 'Start AI chat',
      shortcut: 'Cmd+Enter',
    },
    {
      id: 'explain:clear',
      label: 'Explain: Clear History',
      description: 'Clear chat history',
    },
  ],

  shortcuts: [
    { commandId: 'explain:chat', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['explain', 'ai', 'chat', 'generate', 'llm', 'gpt', '智能'],

  permissions: ['ai:chat', 'network'],

  settings: {
    model: { key: 'model', type: 'select' as const, label: '模型', default: "default" },
    temperature: { key: 'temperature', type: 'number' as const, label: 'Temperature', default: 0.7 },
  },

  history: { enabled: true, maxItems: 20 },
})
