// @ts-nocheck
/**
 * Github Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'github',
  name: 'Github',
  icon: 'GitBranch',
  version: '1.0.0',
  description: 'Enterprise tool — external service integration',
  category: 'utility',

  route: '/github',
  component: () => import('@/features/github/GithubView.vue'),

  commands: [
    {
      id: 'github:connect',
      label: 'Github: Connect',
      description: 'Connect to service',
    },
    {
      id: 'github:sync',
      label: 'Github: Sync',
      description: 'Sync data',
    },
  ],

  shortcuts: [
,
  ],

  keywords: ['github', 'enterprise', 'integration', 'service', '企业', '集成'],

  permissions: ['network', 'storage:read', 'storage:write'],

  settings: {
    apiEndpoint: { key: 'apiEndpoint', type: 'input' as const, label: 'API Endpoint', default: "" },
    apiKey: { key: 'apiKey', type: 'input' as const, label: 'API Key', default: "" },
    autoConnect: { key: 'autoConnect', type: 'toggle' as const, label: '自动连接', default: false },
  },

  history: { enabled: true, maxItems: 20 },
})
