/**
 * Jira Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'jira',
  name: 'Jira',
  icon: '🏢',
  version: '1.0.0',
  description: '企业工具 — 外部服务集成',
  category: 'utility',

  route: '/jira',
  component: () => import('@/features/jira/JiraView.vue'),

  commands: [
    {
      id: 'jira:connect',
      label: 'Jira: Connect',
      description: 'Connect to service',
    },
    {
      id: 'jira:sync',
      label: 'Jira: Sync',
      description: 'Sync data',
    },
  ],

  shortcuts: [
,
  ],

  keywords: ['jira', 'enterprise', 'integration', 'service', '企业', '集成'],

  permissions: ['network', 'storage:read', 'storage:write'],

  settings: {
    apiEndpoint: { key: 'apiEndpoint', type: 'input' as const, label: 'API Endpoint', default: "" },
    apiKey: { key: 'apiKey', type: 'input' as const, label: 'API Key', default: "" },
    autoConnect: { key: 'autoConnect', type: 'toggle' as const, label: '自动连接', default: false },
  },

  history: { enabled: true, maxItems: 20 },
})
