// @ts-nocheck
/**
 * Markdown Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'markdown',
  name: 'Markdown',
  icon: '📝',
  version: '1.0.0',
  description: '编辑器工具 — 格式化、压缩与验证',
  category: 'formatter',

  route: '/markdown',
  component: () => import('@/features/markdown/MarkdownView.vue'),

  commands: [
    {
      id: 'markdown:format',
      label: 'Markdown: Format',
      description: 'Format content',
      shortcut: 'Cmd+Shift+F',
    },
    {
      id: 'markdown:minify',
      label: 'Markdown: Minify',
      description: 'Minify/compress content',
    },
    {
      id: 'markdown:validate',
      label: 'Markdown: Validate',
      description: 'Validate content',
    },
  ],

  shortcuts: [
    { commandId: 'markdown:format', default: 'Ctrl+Shift+F', mac: 'Cmd+Shift+F' },
  ],

  keywords: ['markdown', 'format', 'minify', 'validate', 'editor', 'formatter', 'beautify'],

  permissions: ['clipboard:read', 'clipboard:write', 'file:export'],

  settings: {
    indentSize: { key: 'indentSize', type: 'select' as const, label: '缩进', default: 2 },
    autoFormat: { key: 'autoFormat', type: 'toggle' as const, label: '自动格式化', default: true },
  },

  history: { enabled: true, maxItems: 20 },
})
