// @ts-nocheck
/**
 * Prompt Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'prompt',
  name: 'Prompt',
  icon: 'MessagesSquare',
  version: '1.0.0',
  description: 'AI tools — chat, completion, and generation',
  category: 'ai',

  route: '/prompt',
  component: () => import('@/features/prompt/PromptView.vue'),

  commands: [
    {
      id: 'prompt:chat',
      label: 'Prompt: Chat',
      description: 'Start AI chat',
      shortcut: 'Cmd+Enter',
    },
    {
      id: 'prompt:clear',
      label: 'Prompt: Clear History',
      description: 'Clear chat history',
    },
  ],

  shortcuts: [
    { commandId: 'prompt:chat', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['prompt', 'ai', 'chat', 'generate', 'llm', 'gpt', '智能'],

  permissions: ['ai:chat', 'network'],

  settings: {
    model: { key: 'model', type: 'select' as const, label: '模型', default: "default" },
    temperature: { key: 'temperature', type: 'number' as const, label: 'Temperature', default: 0.7 },
  },

  history: { enabled: true, maxItems: 20 },
})
