/**
 * Qrcode Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'qrcode',
  name: 'Qrcode',
  icon: '👁',
  version: '1.0.0',
  description: '查看器工具 — 预览文件和元数据',
  category: 'utility',

  route: '/qrcode',
  component: () => import('@/features/qrcode/QrcodeView.vue'),

  commands: [
    {
      id: 'qrcode:open',
      label: 'Qrcode: Open File',
      description: 'Open file for viewing',
      shortcut: 'Cmd+O',
    },
  ],

  shortcuts: [
    { commandId: 'qrcode:open', default: 'Ctrl+O', mac: 'Cmd+O' },
  ],

  keywords: ['qrcode', 'view', 'preview', 'open', 'file', '查看', '预览'],

  permissions: ['file:read'],

  settings: {
    autoPreview: { key: 'autoPreview', type: 'toggle' as const, label: '自动预览', default: true },
  },

  history: { enabled: true, maxItems: 20 },
})
