// @ts-nocheck
/**
 * Regex Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'regex',
  name: 'Regex',
  icon: 'FileCode',
  version: '1.0.0',
  description: 'Inspector tool — parse and display structured data',
  category: 'analyzer',
  status: 'coming-soon',

  route: '/regex',
  component: () => import('@/features/regex/RegexView.vue'),

  commands: [
    {
      id: 'regex:parse',
      label: 'Regex: Parse',
      description: 'Parse and inspect',
      shortcut: 'Cmd+Enter',
    },
  ],

  shortcuts: [
    { commandId: 'regex:parse', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['regex', 'inspect', 'parse', 'analyze', 'decode', '解析', '分析'],

  permissions: ['clipboard:read', 'clipboard:write'],

  settings: {
    autoParse: { key: 'autoParse', type: 'toggle' as const, label: 'Auto-parse on Paste', default: true },
  },

  history: { enabled: true, maxItems: 20 },
})
