// @ts-nocheck
/**
 * RequestDecoder Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'request-decoder',
  name: 'RequestDecoder',
  icon: 'Globe',
  version: '1.0.0',
  description: 'Network tool — HTTP request and response analysis',
  category: 'network',

  route: '/request-decoder',
  component: () => import('@/features/request-decoder/RequestDecoderView.vue'),

  commands: [
    {
      id: 'request-decoder:send',
      label: 'RequestDecoder: Send Request',
      description: 'Send HTTP request',
      shortcut: 'Cmd+Enter',
    },
  ],

  shortcuts: [
    { commandId: 'request-decoder:send', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['request-decoder', 'http', 'request', 'api', 'curl', 'rest', 'fetch', '请求'],

  permissions: ['network', 'clipboard:write'],

  settings: {
    defaultMethod: { key: 'defaultMethod', type: 'select' as const, label: '默认方法', default: "GET" },
    timeout: { key: 'timeout', type: 'number' as const, label: '超时(ms)', default: 10000 },
  },

  history: { enabled: true, maxItems: 20 },
})
