// @ts-nocheck
/**
 * Sentry Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'sentry',
  name: 'Sentry',
  icon: 'Shield',
  version: '1.0.0',
  description: 'Enterprise tool — external service integration',
  category: 'enterprise',
  status: 'coming-soon',

  route: '/sentry',
  component: () => import('@/features/sentry/SentryView.vue'),

  commands: [
    {
      id: 'sentry:connect',
      label: 'Sentry: Connect',
      description: 'Connect to service',
    },
    {
      id: 'sentry:sync',
      label: 'Sentry: Sync',
      description: 'Sync data',
    },
  ],

  shortcuts: [
,
  ],

  keywords: ['sentry', 'enterprise', 'integration', 'service', '企业', '集成'],

  permissions: ['network', 'storage:read', 'storage:write'],

  settings: {
    apiEndpoint: { key: 'apiEndpoint', type: 'input' as const, label: 'API Endpoint', default: "" },
    apiKey: { key: 'apiKey', type: 'input' as const, label: 'API Key', default: "" },
    autoConnect: { key: 'autoConnect', type: 'toggle' as const, label: 'Auto Connect', default: false },
  },

  history: { enabled: true, maxItems: 20 },
})
