// @ts-nocheck
/**
 * Sm3 Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'sm3',
  name: 'SM3',
  icon: 'Hash',
  version: '1.0.0',
  description: 'Data conversion tool — input, convert, output',
  category: 'crypto',
  status: 'coming-soon',

  route: '/sm3',
  component: () => import('@/features/sm3/Sm3View.vue'),

  commands: [
    {
      id: 'sm3:execute',
      label: 'Sm3: Execute',
      description: 'Execute transformation',
      shortcut: 'Cmd+Enter',
    },
    {
      id: 'sm3:swap',
      label: 'Sm3: Swap I/O',
      description: 'Swap input and output',
    },
  ],

  shortcuts: [
    { commandId: 'sm3:execute', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['sm3', 'transform', 'convert', 'encode', 'decode', 'encrypt', 'decrypt'],

  permissions: ['clipboard:read', 'clipboard:write'],

  settings: {
    mode: { key: 'mode', type: 'select' as const, label: 'Default Mode', default: "encrypt" },
    inputEncoding: { key: 'inputEncoding', type: 'select' as const, label: 'Input Encoding', default: "utf8" },
    outputEncoding: { key: 'outputEncoding', type: 'select' as const, label: 'Output Encoding', default: "base64" },
  },

  history: { enabled: true, maxItems: 20 },
})
