// @ts-nocheck
/**
 * Sm4 Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'sm4',
  name: 'Sm4',
  icon: '🔐',
  version: '1.0.0',
  description: '数据转换工具 — 输入、转换、输出',
  category: 'crypto',

  route: '/sm4',
  component: () => import('@/features/sm4/Sm4View.vue'),

  commands: [
    {
      id: 'sm4:execute',
      label: 'Sm4: Execute',
      description: 'Execute transformation',
      shortcut: 'Cmd+Enter',
    },
    {
      id: 'sm4:swap',
      label: 'Sm4: Swap I/O',
      description: 'Swap input and output',
    },
  ],

  shortcuts: [
    { commandId: 'sm4:execute', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['sm4', 'transform', 'convert', 'encode', 'decode', 'encrypt', 'decrypt'],

  permissions: ['clipboard:read', 'clipboard:write'],

  settings: {
    mode: { key: 'mode', type: 'select' as const, label: '默认模式', default: "encrypt" },
    inputEncoding: { key: 'inputEncoding', type: 'select' as const, label: '输入编码', default: "utf8" },
    outputEncoding: { key: 'outputEncoding', type: 'select' as const, label: '输出编码', default: "base64" },
  },

  history: { enabled: true, maxItems: 20 },
})
