// @ts-nocheck
/**
 * Uuid Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'uuid',
  name: 'UUID',
  icon: 'Hash',
  version: '1.0.0',
  description: 'Format converter — convert between formats',
  category: 'converter',
  status: 'coming-soon',

  route: '/uuid',
  component: () => import('@/features/uuid/UuidView.vue'),

  commands: [
    {
      id: 'uuid:convert',
      label: 'Uuid: Convert',
      description: 'Convert format',
      shortcut: 'Cmd+Enter',
    },
    {
      id: 'uuid:swap',
      label: 'Uuid: Swap Direction',
      description: 'Swap conversion direction',
    },
  ],

  shortcuts: [
    { commandId: 'uuid:convert', default: 'Ctrl+Enter', mac: 'Cmd+Enter' },
  ],

  keywords: ['uuid', 'convert', 'converter', 'transform', 'switch', '互转'],

  permissions: ['clipboard:read', 'clipboard:write'],

  settings: {
    defaultDirection: { key: 'defaultDirection', type: 'select' as const, label: 'Default Direction', default: "forward" },
  },

  history: { enabled: true, maxItems: 20 },
})
