// @ts-nocheck
/**
 * Xml Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'xml',
  name: 'Xml',
  icon: '📝',
  version: '1.0.0',
  description: '编辑器工具 — 格式化、压缩与验证',
  category: 'formatter',

  route: '/xml',
  component: () => import('@/features/xml/XmlView.vue'),

  commands: [
    {
      id: 'xml:format',
      label: 'Xml: Format',
      description: 'Format content',
      shortcut: 'Cmd+Shift+F',
    },
    {
      id: 'xml:minify',
      label: 'Xml: Minify',
      description: 'Minify/compress content',
    },
    {
      id: 'xml:validate',
      label: 'Xml: Validate',
      description: 'Validate content',
    },
  ],

  shortcuts: [
    { commandId: 'xml:format', default: 'Ctrl+Shift+F', mac: 'Cmd+Shift+F' },
  ],

  keywords: ['xml', 'format', 'minify', 'validate', 'editor', 'formatter', 'beautify'],

  permissions: ['clipboard:read', 'clipboard:write', 'file:export'],

  settings: {
    indentSize: { key: 'indentSize', type: 'select' as const, label: '缩进', default: 2 },
    autoFormat: { key: 'autoFormat', type: 'toggle' as const, label: '自动格式化', default: true },
  },

  history: { enabled: true, maxItems: 20 },
})
