// @ts-nocheck
/**
 * Yaml Plugin — Auto-generated by Plugin Generator
 */

import { definePlugin } from '@/sdk/plugin'

export default definePlugin({
  id: 'yaml',
  name: 'Yaml',
  icon: 'FileCode',
  version: '1.0.0',
  description: 'Editor tool — format, minify, and validate',
  category: 'formatter',

  route: '/yaml',
  component: () => import('@/features/yaml/YamlView.vue'),

  commands: [
    {
      id: 'yaml:format',
      label: 'Yaml: Format',
      description: 'Format content',
      shortcut: 'Cmd+Shift+F',
    },
    {
      id: 'yaml:minify',
      label: 'Yaml: Minify',
      description: 'Minify/compress content',
    },
    {
      id: 'yaml:validate',
      label: 'Yaml: Validate',
      description: 'Validate content',
    },
  ],

  shortcuts: [
    { commandId: 'yaml:format', default: 'Ctrl+Shift+F', mac: 'Cmd+Shift+F' },
  ],

  keywords: ['yaml', 'format', 'minify', 'validate', 'editor', 'formatter', 'beautify'],

  permissions: ['clipboard:read', 'clipboard:write', 'file:export'],

  settings: {
    indentSize: { key: 'indentSize', type: 'select' as const, label: '缩进', default: 2 },
    autoFormat: { key: 'autoFormat', type: 'toggle' as const, label: '自动格式化', default: true },
  },

  history: { enabled: true, maxItems: 20 },
})
